# list of the camera topic prefixes to load for the algorithm. The topic prefixes are required (i.e. /sekonix_camera/port_a_cam_0 for the front centre camera)
# note: do not use the image_color topic, only the prefix /sekonix_camera/XX is required
camera_topics:
  - /sekonix_camera/port_a_cam_0
  - /sekonix_camera/port_a_cam_1
  - /sekonix_camera/port_b_cam_0
  - /sekonix_camera/port_b_cam_1
  - /sekonix_camera/port_c_cam_0
  - /sekonix_camera/port_c_cam_1
  - /sekonix_camera/port_d_cam_0
  - /sekonix_camera/port_d_cam_1